#spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://152.*.*.*:3306/gulimall_ums
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  application:
#    name: gulimall-member
#
##  cloud:
##    sentinel:
##      transport:
##        dashboard: 152.*.*.*:8080
##  zipkin:
##    base-url: http://152.*.*.*:9411
##    sender:
##      type: web
##    discovery-client-enabled: false
##  #采样取值介于 0到1之间，1则表示全部收集
##  sleuth:
##    sampler:
##      probability: 1
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#server:
#  port: 8112
#logging:
#  level:
#    io.niceseason.gulimall.member.dao: debug
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
