server:
  port: 12000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: #nacos注册中心地址
    sentinel:
      transport:
        dashboard: 152.136.194.75:8080
  redis:
    host: 152.136.194.75
  session:
    store-type: redis
  zipkin:
    base-url: http://152.136.194.75:9411
    sender:
      type: web
    discovery-client-enabled: false
  #采样取值介于 0到1之间，1则表示全部收集
  sleuth:
    sampler:
      probability: 1
logging:
  level:
    io.niceseason.gulimall.search.service: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'