spring:
#  zipkin:
#    base-url: http://localhost:9411
#    sender:
#      type: web
#    discovery-client-enabled: false
#  #采样取值介于 0到1之间，1则表示全部收集
#  sleuth:
#    sampler:
#      probability: 1
  cloud:
    alicloud:
      access-key: LTAI4G7Wd8VcTDhae9HpafUp
      secret-key: NFTagK04gdwErDfkC60pnFFzLOVBCd
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-kaikai
      # 发送短信接口的配置
#      sms:
#        host: http://dingxin.market.alicloudapi.com
#        path: /dx/sendSms
#        appcode: #
#    sentinel:
#      transport:
#        dashboard: localhost:8080

  application:
    name: gulimall-third

server:
  port: 30000


management:
  endpoints:
    web:
      exposure:
        include: '*'
