spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://152.136.194.75:3306/gulimall_wms
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: gulimall-ware
#  cloud:
#    sentinel:
#      transport:
#        dashboard: 152.136.194.75:8080
#  rabbitmq:
#    host: #
#    username: niceseason
#    password: mo19960729
#    listener:
#      simple:
#        acknowledge-mode: manual
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#  zipkin:
#    base-url: http://152.136.194.75:9411
#    sender:
#      type: web
#    discovery-client-enabled: false
#  #采样取值介于 0到1之间，1则表示全部收集
#  sleuth:
#    sampler:
#      probability: 1

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 8115

management:
  endpoints:
    web:
      exposure:
        include: '*'
